name: tflite_flutter_helper
description: Easy, fast processing and manipulation of input and output of TensorFlow Lite Models.
version: 0.3.0
homepage: https://github.com/Ramanan05072006/tflite_flutter_helper

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  quiver: ^3.0.1
  path_provider: ^2.1.1
  tflite_flutter:
    git:
      url: https://github.com/Ramanan05072006/flutter-tflite.git
      ref: main  # Make sure this branch exists in your fork
  tuple: ^2.0.0
  camera: ^0.11.0+1
  ffi: ^2.0.1
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tfliteflutter.tflite_flutter_helper
        pluginClass: TfliteFlutterHelperPlugin
      ios:
        pluginClass: TfliteFlutterHelperPlugin
      linux:
        pluginClass: TfliteFlutterHelperPlugin
      macos:
        pluginClass: TfliteFlutterHelperPlugin
      windows:
        pluginClass: TfliteFlutterHelperPlugin
